#Script with all the libraries needed

library(pdftools)
library(qpdf)
library(here)
library(dotenv)
library(stringr)
library(dplyr)
library(ggplot2)
library(moments)
library(openxlsx)
library(rstudioapi)
library(lubridate)
library(future.apply)
library(jsonlite)
library(mime)
library(ellmer)
library(dplyr)
library(readxl)
library(tidyr)
library(forecast)
library(purrr)
library(scales)
library(ggradar)
plan(multisession, workers = 4)
